# Generated by Django 2.1 on 2018-08-26 18:57

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('height', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('hash', models.CharField(db_index=True, max_length=64, validators=[django.core.validators.RegexValidator(code='nomatch', message='Must be a 64 character hex string', regex='^.[a-f0-9]{64}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(code='nomatch', message='Must be a 64 character hex string', regex='^.[a-f0-9]{64}$')])),
                ('output_index', models.PositiveIntegerField()),
                ('block_index', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('NONE', 'NONE'), ('CLAIM', 'CLAIM'), ('OPEN', 'OPEN'), ('BID', 'BID'), ('REVEAL', 'REVEAL'), ('REDEEM', 'REDEEM'), ('REGISTER', 'REGISTER'), ('UPDATE', 'UPDATE'), ('RENEW', 'RENEW'), ('TRANSFER', 'TRANSFER'), ('FINALIZE', 'FINALIZE'), ('REVOKE', 'REVOKE')], max_length=10)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('value', models.BigIntegerField(blank=True, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block', to='explorer.Block')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('hash', models.CharField(max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Must be a 64 character hex string')])),
                ('name', models.CharField(db_index=True, max_length=500, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_height', to='explorer.Block'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-block', '-block_index', '-output_index'], name='explorer_ev_block_i_8149f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('tx_hash', 'output_index')},
        ),
    ]
